name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install

  publish:
    needs: cache-and-install
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@watsuyo'
          cache: 'pnpm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - run: |
          git config --global user.name 'watsuyo'
          git config --global user.email 'watsuyo.dev@gmail.com'
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
